### ISSUE TITLE
One test is always skipped

### ISSUE THREAD

**Issue by frozencemetery** [enarx/tlssock#23]
Let me preface by saying that the test infrastructure in meson.build is inscrutable to me (and that this is why GSSAPI support is still outstanding).

But it definitely appears to my eye that if tests only has a single value, no tests get run, and if I define n tests, meson/ninja are only aware of n-1 of them.

**Comment by npmccallum** [comment]
Figure it out?

**Comment by frozencemetery** [comment]
Yes.  Going to include some notes in PR (hopefully soon).
